# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Update Energy Stats
version: "1.2.0"
slug: example
description: Update historical energy stats
url: "https://github.com/jaimani/home-assistant-addons/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
# image: "ghcr.io/home-assistant/{arch}-addon-example"
